# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_dialog.ui'
#
# Created: Wed Nov  6 23:47:55 2013
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 564, 652))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.manga_image_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manga_image_label.sizePolicy().hasHeightForWidth())
        self.manga_image_label.setSizePolicy(sizePolicy)
        self.manga_image_label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.manga_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.manga_image_label.setObjectName("manga_image_label")
        self.horizontalLayout_2.addWidget(self.manga_image_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 250))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushSettings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushSettings.setObjectName("pushSettings")
        self.horizontalLayout_3.addWidget(self.pushSettings)
        self.pushAbout = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushAbout.setObjectName("pushAbout")
        self.horizontalLayout_3.addWidget(self.pushAbout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.volume_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.volume_label.setObjectName("volume_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.volume_label)
        self.chapter_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.chapter_label.setObjectName("chapter_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.chapter_label)
        self.page_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.page_label.setObjectName("page_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.page_label)
        self.list_manga = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.list_manga.setObjectName("list_manga")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.list_manga)
        self.list_volume = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.list_volume.setObjectName("list_volume")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.list_volume)
        self.list_chapter = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.list_chapter.setObjectName("list_chapter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.list_chapter)
        self.list_page = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.list_page.setObjectName("list_page")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.list_page)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyMangaReader"))
        self.manga_image_label.setText(_translate("MainWindow", "Manga Image"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushSettings.setText(_translate("MainWindow", "Settings"))
        self.pushAbout.setText(_translate("MainWindow", "About"))
        self.volume_label.setText(_translate("MainWindow", "TextLabel"))
        self.chapter_label.setText(_translate("MainWindow", "TextLabel"))
        self.page_label.setText(_translate("MainWindow", "TextLabel"))

