# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_settings.ui'
#
# Created: Wed Nov  6 23:47:55 2013
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(416, 278)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SettingsDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushAddMangaDir = QtWidgets.QPushButton(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushAddMangaDir.sizePolicy().hasHeightForWidth())
        self.pushAddMangaDir.setSizePolicy(sizePolicy)
        self.pushAddMangaDir.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushAddMangaDir.setIcon(icon)
        self.pushAddMangaDir.setObjectName("pushAddMangaDir")
        self.horizontalLayout.addWidget(self.pushAddMangaDir)
        self.pushRemoveMangaDir = QtWidgets.QPushButton(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushRemoveMangaDir.sizePolicy().hasHeightForWidth())
        self.pushRemoveMangaDir.setSizePolicy(sizePolicy)
        self.pushRemoveMangaDir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushRemoveMangaDir.setIcon(icon1)
        self.pushRemoveMangaDir.setObjectName("pushRemoveMangaDir")
        self.horizontalLayout.addWidget(self.pushRemoveMangaDir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listMangaDirs = QtWidgets.QListWidget(SettingsDialog)
        self.listMangaDirs.setObjectName("listMangaDirs")
        item = QtWidgets.QListWidgetItem()
        self.listMangaDirs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMangaDirs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMangaDirs.addItem(item)
        self.verticalLayout.addWidget(self.listMangaDirs)
        self.label_3 = QtWidgets.QLabel(SettingsDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelMangaSettings = QtWidgets.QLabel(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMangaSettings.sizePolicy().hasHeightForWidth())
        self.labelMangaSettings.setSizePolicy(sizePolicy)
        self.labelMangaSettings.setAutoFillBackground(False)
        self.labelMangaSettings.setStyleSheet("border: 2px solid grey")
        self.labelMangaSettings.setObjectName("labelMangaSettings")
        self.horizontalLayout_2.addWidget(self.labelMangaSettings)
        self.pushSelectMangaSettingsDir = QtWidgets.QPushButton(SettingsDialog)
        self.pushSelectMangaSettingsDir.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/open_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushSelectMangaSettingsDir.setIcon(icon2)
        self.pushSelectMangaSettingsDir.setObjectName("pushSelectMangaSettingsDir")
        self.horizontalLayout_2.addWidget(self.pushSelectMangaSettingsDir)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(SettingsDialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelUnrarExe = QtWidgets.QLabel(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUnrarExe.sizePolicy().hasHeightForWidth())
        self.labelUnrarExe.setSizePolicy(sizePolicy)
        self.labelUnrarExe.setAutoFillBackground(False)
        self.labelUnrarExe.setStyleSheet("border: 2px solid grey")
        self.labelUnrarExe.setObjectName("labelUnrarExe")
        self.horizontalLayout_3.addWidget(self.labelUnrarExe)
        self.pushSelectUnrarExecutable = QtWidgets.QPushButton(SettingsDialog)
        self.pushSelectUnrarExecutable.setText("")
        self.pushSelectUnrarExecutable.setIcon(icon2)
        self.pushSelectUnrarExecutable.setObjectName("pushSelectUnrarExecutable")
        self.horizontalLayout_3.addWidget(self.pushSelectUnrarExecutable)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "PyMangaReader Settings"))
        self.label.setText(_translate("SettingsDialog", "Manga Directories"))
        __sortingEnabled = self.listMangaDirs.isSortingEnabled()
        self.listMangaDirs.setSortingEnabled(False)
        item = self.listMangaDirs.item(0)
        item.setText(_translate("SettingsDialog", "1"))
        item = self.listMangaDirs.item(1)
        item.setText(_translate("SettingsDialog", "2"))
        item = self.listMangaDirs.item(2)
        item.setText(_translate("SettingsDialog", "3"))
        self.listMangaDirs.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("SettingsDialog", "Manga settings (last viewed page)"))
        self.labelMangaSettings.setText(_translate("SettingsDialog", "TextLabel"))
        self.label_4.setText(_translate("SettingsDialog", "Unrar executable (if not in PATH)"))
        self.labelUnrarExe.setText(_translate("SettingsDialog", "TextLabel"))

import images_res_rc
